title: Calxus Blog
description: Calxus' personal blog to document the mischief of a DevSecOps Engineer 
permalink: ':title/'
baseurl: "/"
url: "https://calxus.github.io"

author: Calxus
author-img: calxus.png # add your photo
about-author: I am a DevOps Engineer with a penchant for Pentesting and proud owner of an over-engineered home network
social-twitter: calxus
social-github: calxus
social-email: calxus@protonmail.ch

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
